version: '3'
services:
  java:
    container_name: modularizr_java
    image: azul/zulu-openjdk-alpine:13
    environment:
      - "kafka1:9091,kafka2:9092,kafka3:9093"
    volumes:
      - "./target:/home/app"
      - "./resources:/resources"
    ports:
      - "8081:8080"
      - "8001:8000"
    command: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -jar /home/app/spreadr-0.0.1-SNAPSHOT.jar
    restart: always
    depends_on:
      - postgres
      - mysql
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
  postgres:
    image: postgres:9.6
    container_name: modularizr_postgres
    restart: always
    environment:
      - POSTGRES_DB=publisaiz
      - POSTGRES_PASSWORD=!!??krykiet123
      - POSTGRES_USER=korsarz
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
  mysql:
    image: mysql:5.7
    container_name: modularizr_mysql
    restart: 'always'
    command: --sql_mode="" --max_allowed_packet=325058560
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: arthub
      MYSQL_DATABASE: arthub
      MYSQL_USER: arthub
      MYSQL_PASSWORD: arthub
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: modularizr_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '88:80'
    volumes:
      - ./sessions
  phppgadmin:
    container_name: modularizr_pgadmin
    image: dockage/phppgadmin
    ports:
      - "99:80"
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=publisaiz
  zookeeper:
    container_name: modularizr_zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
  kafka1:
    container_name: modularizr_kafka1
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_LOG_RETENTION_HOURS=-1
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
      - ZOOKEEPER=localhost:2181
    volumes:
      - ./data/kafka/kafka1:/var/lib/kafka/data
  kafka2:
    container_name: modularizr_kafka2
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_LOG_RETENTION_HOURS=-1
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
      - ZOOKEEPER=zookeeper:2181
    volumes:
      - ./data/kafka/kafka2:/var/lib/kafka/data
  kafka3:
    container_name: modularizr_kafka3
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_LOG_RETENTION_HOURS=-1
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,x:9093
      - ZOOKEEPER=zookeeper:2181
    volumes:
      - ./data/kafka/kafka3:/var/lib/kafka/data